preprocess:
  input_dir: data/raw/UCRArchive_2018
  output_dir: data/processed
  datasets: ["Beef",]  # or ["GunPoint", "Coffee" ...]
  models: ["mlp", "kan"] # InceptionTime uses MLPs preprocessed data

train_mlp:
  depths: [2] 
  hidden_layers: [50] 
  learning_rates: [0.001]
  seeds: [42]
  epochs: [500]
  batch: 16

train_kan:
  depths: [2] 
  hidden_layers: [20] 
  learning_rates: [0.001]
  epochs: [500]
  batch: 16
  grid: [5] 
  spline_order: 3 

train_inceptiontime:
  depths: [6] 
  learning_rates: [0.001]
  epochs: [500]
  batch: 16
  n_convolutions: [3]
  n_filters: [32]
  kernel_sizes: [32]

train_drtp:
  depths: [2]
  hidden_layers: [20]
  learning_rates: [0.001]
  epochs: [500]
  batch: 16

train_noprop:
  ts: [10]
  learnable_embs: [False, True]
  emb_dimensions: [20]
  etas: [0.1, 1]
  learning_rates: [0.001]
  weight_decays: [0.001]
  epochs: [70]
  batch: 16